messages:
  prefix: '&8(&3ChatAddons&8)&r '
  reload: '&aConfig reloaded&8!'
  unknown-command: '&cUnknown command&8.'
  no-permission: "&cYou don't have the permission to use this command&8!"
  help:
    - ''
    - '&8&m        &8« &3ChatAddons &eHelp &8»&m        '
    - '&8/&3ca &bhelp&8: &7displays this list'
    - '&8/&3ca &breload&8: &7reloads the plugin config'
    - '&8/&3ca &bclearchat &8| &bcc&8: &7clears the chat'
    - '&8/&3ca &blockchat &8| &blc&8: &7locks the chat'
    - '&8/&3ca &bunlockchat &8| &buc&8: &7cunlocks the chat'
    - '&8@&3message&8: &7sends message in staff chat'

bracket-placeholders-injector:
  enabled: true

chat-hover:
  enabled: true
  format:
    - '%luckperms_meta_rank_tag% %luckperms_prefix%%essentials_nickname%'
    - '&3✵ &#A7A2A2Balance&8: &2%vault_eco_balance_formatted%'
    - '&3✵ &#A7A2A2Ping: &#B56802%player_ping%'
    - '&3✵ &#A7A2A2XP&8: &#4295D8%player_level%'
    - ''
    - '&8« &#12950bS&#13a10cl&#15ac0di&#16b80em&#18c40ee&#19d00ff&#1bdb10u&#1ce711n &8»'
    - '&3✵ &#A7A2A2Title&8: &#B42745%slimefun_researches_title%'
    - '&3✵ &#A7A2A2XP spent&8: &#4295D8%slimefun_researches_total_xp_levels_spent%'
    - '&3✵ &#A7A2A2Researches&8: &#EF8903%slimefun_researches_total_researches_unlocked%&8/&#CE7603%slimefun_researches_total_researches% &8&o(&#FCFC54&o%slimefun_researches_percentage_researches_unlocked%%&8&o)'
    - ''
    - '&#A7A2A2&oClick to send %luckperms_prefix%&o%essentials_nickname% &#A7A2A2&oa message&8&o!'
  click-action:
    - '/msg %essentials_nickname% '

clear-chat:
  amount: 150
  notify: '&7The chat was cleared by &4{name}&8!'

lock-chat:
  deny: "&7You cannot type in the chat while it's locked&8."
  notify:
    locked: '&7The chat was locked by &4{name}&8!'
    unlocked: '&7The chat was unlocked by &4{name}&8!'
  already:
    locked: '&7The chat is already locked&8!'
    unlocked: '&7The chat is already unlocked&8!'

staff-chat:
  char: '@'
  format: '&3Staff &8&l» &7{name}&8: &b{message}'
