main: me.defaultybuf.chataddons.Main
name: ChatAddons
version: 1.8.0
description: Multiple chat addons
api-version: 1.19
author: DefaultyBuf
softdepend: [PlaceholderAPI]

commands:
  chataddons:
    description: access to main command
    aliases: ca
    permission: chataddons.use
    usage: 'Usage: /chataddons [reload]'

permissions:
  chataddons.admin:
    default: false
    children:
      chataddons.use: true
      chataddons.reload: true
      chataddons.help: true
      chataddons.clearchat.*: true
      chataddons.lockchat.*: true
      chataddons.staffchat: true
      chataddons.mention.*: true
      chataddons.broadcast.*: true

  # -----------------------------------------------------------------
  chataddons.use:
    description: access to use main command
    default: false

  chataddons.reload:
    description: access to reload config
    default: false

  chataddons.help:
    description: access to use chataddons help command
    default: false

  # -----------------------------------------------------------------
  chataddons.clearchat.*:
    default: false
    children:
      chataddons.clearchat: true
      chataddons.clearchat.bypass: true
      chataddons.clearchat.notify: true

  chataddons.clearchat:
    description: access to use clearchat command
    default: false

  chataddons.clearchat.bypass:
    description: access to bypass the clear chat
    default: false

  chataddons.clearchat.notify:
    description: notifies who cleared the chat
    default: false

  # -----------------------------------------------------------------
  chataddons.lockchat.*:
    default: false
    children:
      chataddons.lockchat: true
      chataddons.lockchat.bypass: true
      chataddons.lockchat.notify: true

  chataddons.lockchat:
    description: locks the chat
    default: false

  chataddons.lockchat.bypass:
    description: bypasses the chat lock
    default: false

  chataddons.lockchat.notify:
    description: notifies who locked the chat
    default: false

  # -----------------------------------------------------------------
  chataddons.staffchat:
    description: allows staffchat
    default: false

  # -----------------------------------------------------------------
  chataddons.mention.*:
    default: false
    children:
      chataddons.mention: true
      chataddons.mention.notify: true

  chataddons.mention:
    description: access to mention system
    default: false

  chataddons.mention.notify:
    description: access to be notified
    default: false

  # -----------------------------------------------------------------
  chataddons.broadcast.*:
    default: false
    children:
      chataddons.broadcast: true
      chataddons.broadcast.receive: true

  chataddons.broadcast:
    description: access to broadcast
    default: false

  chataddons.broadcast.receive:
    description: access to receive broadcast messages
    default: false
